spring:
  application.name: later
  main.banner-mode: OFF
  jpa:
    show-sql: true
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
  datasource:
    username: "dbuser"
    password: "12345"
    url: "jdbc:postgresql://localhost:5432/later"
    driver-class-name: "org.postgresql.Driver"

    # вывод запросов
logging.level.org.hibernate:
  SQL: DEBUG
    # вывод значений, которые подставляются в параметры запросов
  orm.jdbc.bind: trace